configured_endpoints: 83
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/moonbase/moonbase-sdk-df34aa7c5d0a75ffbe3293b788142fd0abd79703cd4da78ce26fc5d6ea0fbcbc.yml
openapi_spec_hash: f194aabdcebd382a1266fcba9d01d13b
config_hash: dbc0aa4f4394c4c4996ff86d273a7927
